// <auto-generated />
using System;
using CountNextTaskDate.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CountNextTaskDate.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20230902122722_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CountNextTaskDate.Models.NextTaskResponse", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("count")
                        .HasColumnType("int");

                    b.Property<DateTime>("currentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("firstOccurrence")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("lastOccurrence")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("nextOccurrence")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("Responses");
                });
#pragma warning restore 612, 618
        }
    }
}
